version: '3.7'

services:
  kc-auth-service:
    image: quay.io/keycloak/keycloak:26.2.5
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 1111
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak_db
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root_password
    ports:
      - 1111:1111
    volumes:
      - ./themes/idp-only:/opt/keycloak/themes/idp-only
    restart: always
